### ISSUE TITLE
Registration Background Service

### ISSUE THREAD

**Issue by huttneab** [TrustTheVote-Project/Grommet#14]
Requirements:
- run after new registration is complete
- check for pending registrations to upload when we have internet connection
- remove completed uploads from local db / or update the status to "complete"
- process uploads sequentially

Design:
- Things that kick it off
  -- when the app starts, set up a network listener that kicks off the service when we get internet connection
- When a registration is complete
- once on upload call completes it should check to see if there are anymore
- each request is only a couple seconds (tops) so we shouldn't need a wakeful service

**TODO**
- [x] create JSON serialization classes
- [x] create IntentService to make the requests
- [x] wire up network connectivity watcher and kick it off when we have network connectivity changes (from none to connected)
- [x] launch intent when a registration is complete
- [x] clean up abandoned registrations at the end of each run
